version: '3'
services: 
  movies:
    build:
      dockerfile: ./docker/movies.dockerfile
      context: .
    image: julianneportugal/movies
    container_name: movies
    ports: 
      - "80:80"
    networks: 
      - films-network
    depends_on:
      - "redis"
  redis: 
    image: redis
    command: redis-server
    networks: 
      - films-network
    ports:
      - "6379:6379"
networks: 
  films-network: 
    driver: bridge